### ISSUE TITLE
Backdrop full page height issue

### ISSUE THREAD

**Issue by hamedtaha** [Zak-C/ngx-loading#21]
Hello guys,
there is a CSS issue regarding the backdrop 
in the backdrop style the position style is absolute and in some cases this style cause the backdrop Div not to fill the height of the page and i think better to be set to Fixed rather than absolute and this will fix the issue

**Comment by Zak-C** [comment]
Hi @hamedtaha 

This is not an issue and is actually the intended behaviour, so that the loading component can be applied to a specific component, which may not fill the whole page. 

There is a configuration option that will give you the functionality you require, which is highlighted in the documentation. Just set 'fullScreenBackdrop' to true within the ngx-loading configuration options. 

Thanks

**Comment by hamedtaha** [comment]
thanks Zak-C for your reply and thanks for clarifying this issue for me
